### ISSUE TITLE
Request:  Config options for sites

### ISSUE THREAD

**Issue by sgath** [vilarion/WoWProgressLink#1]
I love this mod - I was going to build it myself actually, but saw you already did it.

Super helpful.  1 suggestion:

Can we add custom sites and custom URLs in a config...

e.g. right now I look people up on wowprogress or raider io - but I sometimes use warcraftlogs which also has a predefined url.  

Can this be something that you enable as self managed / with defaults?

**Comment by vilarion** [comment]
Yes! I am already working on that. Working out the UI parts takes most of the time, though. Should be done soon.

**Comment by vilarion** [comment]
Hey, I just added Warcraft Logs and and Blizzard Armory.
Regarding custom sites: That is quite a hassle, since every site uses different syntax for realm names. This would require quite a bit of understanding on the user's part which filters to select to transform realm names from ingame output to the sites syntax. Also you would need to be able to input override lists for exceptions.
Frankly the UI coding alone isn't worth it. I can easily add support for more sites if interesting ones pop up. 
If someone wants to write a patch though, they are welcome to do so.
